version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
    environment:
      SERVER_INTERNAL_PORT: ${SERVER_INTERNAL_PORT}
      SERVER_ENTERNAL_PORT: ${SERVER_EXTERNAL_PORT}
      CONTEXT_PATH: ${CONTEXT_PATH}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_INTERNAL_PORT: ${MYSQL_INTERNAL_PORT}
      SPRING_PROFILES_ACTIVE: 'production'
      TZ: ${TZ}
      LOG_FOLDER: ${LOG_FOLDER}
      SPRING_RABBITMQ_HOST: ${RABBIT_MQ_HOST}
      RABBIT_MQ_PORT: ${RABBIT_MQ_PORT}
      RABBIT_MQ_USERNAME: ${RABBIT_MQ_USERNAME}
      RABBIT_MQ_PASSWORD: ${RABBIT_MQ_PASSWORD}
    ports:
      -  ${SERVER_INTERNAL_PORT}:${SERVER_EXTERNAL_PORT}
